# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 574)
        self.le_query = QtWidgets.QLineEdit(Dialog)
        self.le_query.setGeometry(QtCore.QRect(10, 50, 211, 25))
        self.le_query.setObjectName("le_query")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 171, 17))
        self.label.setObjectName("label")
        self.btn_search = QtWidgets.QPushButton(Dialog)
        self.btn_search.setGeometry(QtCore.QRect(290, 50, 89, 25))
        self.btn_search.setObjectName("btn_search")
        self.sp_limit = QtWidgets.QSpinBox(Dialog)
        self.sp_limit.setGeometry(QtCore.QRect(70, 80, 44, 26))
        self.sp_limit.setObjectName("sp_limit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 51, 17))
        self.label_2.setObjectName("label_2")
        self.cb_only_stops = QtWidgets.QCheckBox(Dialog)
        self.cb_only_stops.setGeometry(QtCore.QRect(140, 80, 191, 23))
        self.cb_only_stops.setObjectName("cb_only_stops")
        self.tbl_results = QtWidgets.QTableWidget(Dialog)
        self.tbl_results.setGeometry(QtCore.QRect(0, 120, 391, 231))
        self.tbl_results.setObjectName("tbl_results")
        self.tbl_results.setColumnCount(5)
        self.tbl_results.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_results.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_results.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_results.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_results.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_results.setHorizontalHeaderItem(4, item)
        self.lbl_status = QtWidgets.QLabel(Dialog)
        self.lbl_status.setGeometry(QtCore.QRect(30, 380, 67, 17))
        self.lbl_status.setObjectName("lbl_status")
        self.btn_copy = QtWidgets.QPushButton(Dialog)
        self.btn_copy.setGeometry(QtCore.QRect(20, 470, 89, 25))
        self.btn_copy.setObjectName("btn_copy")
        self.btn_select = QtWidgets.QPushButton(Dialog)
        self.btn_select.setGeometry(QtCore.QRect(140, 470, 89, 25))
        self.btn_select.setObjectName("btn_select")
        self.btn_close = QtWidgets.QPushButton(Dialog)
        self.btn_close.setGeometry(QtCore.QRect(250, 470, 89, 25))
        self.btn_close.setObjectName("btn_close")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "StopFinder"))
        self.label.setText(_translate("Dialog", "Haltestelle suchen ..."))
        self.btn_search.setText(_translate("Dialog", "Suchen"))
        self.label_2.setText(_translate("Dialog", "max."))
        self.cb_only_stops.setText(_translate("Dialog", "nur Haltestellen (stop)"))
        item = self.tbl_results.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name"))
        item = self.tbl_results.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Typ"))
        item = self.tbl_results.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Qualität"))
        item = self.tbl_results.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Best"))
        item = self.tbl_results.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "ID"))
        self.lbl_status.setText(_translate("Dialog", "Bereit."))
        self.btn_copy.setText(_translate("Dialog", "ID kopieren"))
        self.btn_select.setText(_translate("Dialog", "Übernehmen"))
        self.btn_close.setText(_translate("Dialog", "Schließen"))
