# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(580, 661)
        self.le_query = QtWidgets.QLineEdit(Dialog)
        self.le_query.setGeometry(QtCore.QRect(10, 50, 211, 25))
        self.le_query.setObjectName("le_query")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 171, 17))
        self.label.setObjectName("label")
        self.btn_search = QtWidgets.QPushButton(Dialog)
        self.btn_search.setGeometry(QtCore.QRect(230, 50, 89, 25))
        self.btn_search.setObjectName("btn_search")
        self.sp_limit_deps = QtWidgets.QSpinBox(Dialog)
        self.sp_limit_deps.setGeometry(QtCore.QRect(530, 50, 44, 26))
        self.sp_limit_deps.setMaximum(100)
        self.sp_limit_deps.setProperty("value", 20)
        self.sp_limit_deps.setObjectName("sp_limit_deps")
        self.tbl_stops = QtWidgets.QTableWidget(Dialog)
        self.tbl_stops.setGeometry(QtCore.QRect(0, 90, 581, 260))
        self.tbl_stops.setObjectName("tbl_stops")
        self.tbl_stops.setColumnCount(1)
        self.tbl_stops.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_stops.setHorizontalHeaderItem(0, item)
        self.btn_apply = QtWidgets.QPushButton(Dialog)
        self.btn_apply.setGeometry(QtCore.QRect(10, 620, 120, 25))
        self.btn_apply.setObjectName("btn_apply")
        self.btn_close = QtWidgets.QPushButton(Dialog)
        self.btn_close.setGeometry(QtCore.QRect(140, 620, 120, 25))
        self.btn_close.setObjectName("btn_close")
        self.tbl_departures = QtWidgets.QTableWidget(Dialog)
        self.tbl_departures.setGeometry(QtCore.QRect(0, 350, 581, 260))
        self.tbl_departures.setObjectName("tbl_departures")
        self.tbl_departures.setColumnCount(4)
        self.tbl_departures.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_departures.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_departures.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_departures.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_departures.setHorizontalHeaderItem(3, item)
        self.sp_limit_stops = QtWidgets.QSpinBox(Dialog)
        self.sp_limit_stops.setGeometry(QtCore.QRect(530, 20, 44, 26))
        self.sp_limit_stops.setProperty("value", 10)
        self.sp_limit_stops.setObjectName("sp_limit_stops")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(360, 30, 141, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(360, 50, 141, 20))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "StopFinder"))
        self.label.setText(_translate("Dialog", "Haltestelle suchen ..."))
        self.btn_search.setText(_translate("Dialog", "Suchen"))
        item = self.tbl_stops.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Haltestelle"))
        self.btn_apply.setText(_translate("Dialog", "Übernehmen"))
        self.btn_close.setText(_translate("Dialog", "Schließen"))
        item = self.tbl_departures.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Zeit"))
        item = self.tbl_departures.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Linie"))
        item = self.tbl_departures.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Richtung"))
        item = self.tbl_departures.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Bahnsteig"))
        self.label_3.setText(_translate("Dialog", "Anzahl Haltestellen"))
        self.label_4.setText(_translate("Dialog", "Anzahl Abfahrten"))
